[project]
name = "identifier"
version = "0.4.0"
description = "Identifier Service"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
identifier = "identifier.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
extend = "../../ruff.toml"
