[project]
name = "identifier"
version = "0.1.0"
description = "Identifier Service"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
