[project]
name = "broker"
version = "0.1.0"
description = "Message Broker Service"
requires-python = ">=3.12"
dependencies = [
    "pyzmq>=25.1.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
